language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - DJANGO_PACKAGE="django>=1.9,<1.10"
  - DJANGO_PACKAGE="django>=1.8,<1.9"
  - DJANGO_PACKAGE="django>=1.7,<1.8"
  - DJANGO_PACKAGE="django>=1.6,<1.7"
  - DJANGO_PACKAGE="django>=1.5,<1.6"
  - DJANGO_PACKAGE="django>=1.4,<1.5"

matrix:
  # Release candiate status
  allow_failures:

install:
  - pip install -q $DJANGO_PACKAGE six
  - pip install coveralls

script: coverage run django_app_test/runner.py django_extras

after_success:
  - coveralls
