language: python

env:
  - DJANGO_PACKAGE="django>=1.6,<1.7"
  - DJANGO_PACKAGE="django>=1.5,<1.6"
  - DJANGO_PACKAGE="django>=1.4,<1.5"

python:
  - "2.7"

branches:
  only:
    - master
    #- development

install:
  - pip install -q $DJANGO_PACKAGE six --use-mirrors
  - pip install coveralls --use-mirrors

script: python -mdjango_app_test.runner django_extras

after_success:
  - coveralls
