language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - DJANGO="django>=1.9,<1.10"
  - DJANGO="django>=1.8,<1.9"
  - DJANGO="django>=1.7,<1.8"

matrix:
  include:
    - python: "2.7"
      env: DJANGO="django>=1.6,<1.7"
    - python: "2.7"
      env: DJANGO="django>=1.5,<1.6"
    - python: "2.7"
      env: DJANGO="django>=1.4,<1.5"

install:
  - pip install -q $DJANGO six
  - pip install coveralls

script: coverage run django_app_test/runner.py django_extras

after_success:
  - coveralls
